### ISSUE TITLE
"must have size 1024x1024 pixels"

### ISSUE THREAD

**Issue by ghost** [choffmeister/adobe-illustrator-icnsexport#9]
I always get this error when trying to export the file through the script "Your document has size 15x13.294921875 pixels, but must have size 1024x1024 pixels". 
I tried changing the sizes to 15x15 in the script but without luck. And when i do save them in 1024x1024 i get a message saying i must save it first even though i did.

What am i doing wrong here?
Im using Adobe Illustrator CS6

**Comment by choffmeister** [comment]
The 1024 pixel enforcement is just something I think makes sense, because the script scales down to several other smaller images sizes which are also a power of 2. If this is a problem for you you can just drop this check from the script.

Why Illustrator is giving you this message I don't know. Have you reopened Illustrator after changing resolution and saving and is it then still complaining?

**Comment by ghost** [comment]
Sorry for late answer. I tried it now and it went fine.

 Is there a reason the document must be saved first? I tried the script without the check (the if condition which also contains the alert: You must save your document before exporting it ) and it still shows. Maybe this is from illustrator and not the script. 

Anyways, awesome script! It´s nice to be able to make mac icons with illustrator.
